package com.example.be.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.example.be.entities.base.IBaseEntity;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@DynamoDBTable(tableName = "university")
public class University implements IBaseEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private @NonNull String id;
    @DynamoDBAttribute
    private @NonNull String name;
    @DynamoDBAttribute
    private @NonNull String studentEmailDomain;

    public University(@NonNull String name, @NonNull String studentEmailDomain) {
        this.name = name;
        this.studentEmailDomain = studentEmailDomain;
    }
}
