export const tags: string[] = [
  // Programming Languages
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Rust",
  "PHP",
  "C#",
  "TypeScript",
  "Perl",
  "Scala",
  "Haskell",
  "Lua",
  "Objective-C",
  "Shell Scripting",
  "MATLAB",

  // Frameworks
  "Angular",
  "React",
  "React-Native",
  "Vue.js",
  "Spring Boot",
  "Django",
  "Ruby on Rails",
  "Express.js",
  "Flask",
  "Laravel",
  "ASP.NET",
  "Node.js",
  "Symfony",
  "Hibernate",
  "Flutter",
  "Electron",
  "Unity",
  "jQuery",
  "Ember.js",
  "Backbone.js",
  "ASP.NET Core",
  "Meteor",
  "Gatsby",
  "Next.js",
  "NestJS",
  "Quarkus",
  "PyTorch",
  "TensorFlow",
  "Keras",
  "Scikit-learn",
  "NumPy",
  "Pandas",
  "RubyMotion",
  "Phoenix",
  "Grails",
  "CakePHP",
  "CodeIgniter",
  "Zend Framework",

  // Subdomains of Computer Science
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Deep Learning (DL)",
  "Natural Language Processing (NLP)",
  "Computer Vision (CV)",
  "Data Science",
  "Big Data",
  "Blockchain",
  "CyberSecurity",
  "Cloud Computing",
  "Internet of Things (IoT)",
  "Web Development",
  "Mobile Development",
  "Database Management",
  "Operating Systems",
  "Algorithms",
  "Data Structures",
  "Computer Networks",
  "Software Engineering",
  "Hardware Engineering",
  "Robotics",
  "Virtual Reality (VR)",
  "Augmented Reality (AR)",
  "Game Development",
  "Human-Computer Interaction (HCI)",
  "Parallel Computing",
  "Quantum Computing",
  "Compiler Design",
  "Computer Graphics",
  "Data Mining",
  "Information Retrieval",
  "Network Security",
  "Cryptography",
  "UX/UI Design",
  "API Development",
  "DevOps",
  "Microservices",
  "Serverless Computing",
  "Testing and QA",
  "Agile Methodologies",
  "Version Control (Git, SVN)",
  "Continuous Integration/Continuous Delivery (CI/CD)",
  "Containerization",
  "Scalability",
  "Performance Optimization",
  "Data Visualization",
  "Image Processing",
  "Speech Recognition",
  "ChatBot Development",
  "E-commerce Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Data Warehousing",
  "Business Intelligence",
  "UI Automation",
  "Natural Language Generation (NLG)",
  "Semantic Web",
  "Geographic Information Systems (GIS)",
  "WireFraming",
  "Responsive Design",

  // Cloud Platforms
  "Google Cloud Platform (GCP)",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "IBM Cloud",
  "Oracle Cloud",
  "DigitalOcean",
  "Heroku",
  "Firebase",

  // Tools
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "SonarQube",
  "Selenium",
  "Postman",
  "New Relic",
  "Splunk",
  "ELK Stack",
  "Grafana",
  "Prometheus",
  "Eclipse",
  "Visual Studio",
  "IntelliJ IDEA",
  "PyCharm",
  "WebStorm",
  "Sublime Text",
  "Atom",
  "Visual Studio Code",
  "Notepad++",
  "VirtualBox",
  "Vagrant",
  "Ansible",
  "Puppet",
  "Chef",
  "Kafka",
  "RabbitMQ",
  "Elasticsearch",
  "Redis",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Oracle Database",
  "SQLite",
  "GraphQL",
  "RESTful API",
  "SOAP",
  "OAuth",
  "JSON",
  "XML",
  "YAML",
  "HTML",
  "CSS",
  "Bootstrap",
  "Material-UI",
  "Tailwind CSS",
  "SASS",
  "LESS",
  "Webpack",
  "Babel",
  "Gulp",
  "Grunt",
  "NPM",
  "Yarn",
  "Bower",
  "iOS",
  "Android",
  "Linux",
  "Ubuntu",
  "Unix",
  "Windows",
  "Raspberry Pi",
  "Arduino"
];

/**
 *  A dex for tags used for job entry cards, to display abbreviations for really long tags
 *  For example: "Continuous Integration/Continuous Delivery (CI/CD)" will appear as "CI/CD" in the tag
  */
export const tagsAbbreviations: Record<string, string> = {
  "Artificial Intelligence (AI)": "AI",
  "Machine Learning (ML)": "ML",
  "Deep Learning (DL)": "DL",
  "Natural Language Processing (NLP)": "NLP",
  "Computer Vision (CV)": "CV",
  "Internet of Things (IoT)": "IoT",
  "Virtual Reality (VR)": "VR",
  "Augmented Reality (AR)": "AR",
  "Human-Computer Interaction (HCI)": "HCI",
  "Continuous Integration/Continuous Delivery (CI/CD)": "CI/CD",
  "Natural Language Generation (NLG)": "NLG",
  "Geographic Information Systems (GIS)": "GIS",
  "Google Cloud Platform (GCP)": "GCP",
  "Amazon Web Services (AWS)": "AWS",
}

export const locations: string[] = [
  "United Kingdom",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Bristol, United Kingdom",
  "Edinburgh, United Kingdom",
  "Glasgow, United Kingdom",
  "Cambridge, United Kingdom",
  "Oxford, United Kingdom",
  "Leeds, United Kingdom",
  "Brighton, United Kingdom",
  "Birmingham, United Kingdom",
  "Newcastle, United Kingdom",
  "Reading, United Kingdom",
  "Liverpool, United Kingdom",
  "Sheffield, United Kingdom",
  "Southampton, United Kingdom",
  "Nottingham, United Kingdom",
  "York, United Kingdom",
  "Bath, United Kingdom",
  "Leicester, United Kingdom",
  "Aberdeen, United Kingdom",
  "Ireland",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Galway, Ireland",
  "Limerick, Ireland",
  "Waterford, Ireland",
  "Reykjavik, Iceland",
  "Norway",
  "Oslo, Norway",
  "Trondheim, Norway",
  "Sweden",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Malmo, Sweden",
  "Finland",
  "Helsinki, Finland",
  "Oulu, Finland",
  "Tampere, Finland",
  "Turku, Finland",
  "Estonia",
  "Talinn, Estonia",
  "Latvia",
  "Riga, Latvia",
  "Denmark",
  "Copenhagen, Denmark",
  "Aarhus, Denmark",
  "Aalborg, Denmark",
  "Poland",
  "Warsaw, Poland",
  "Gdansk, Poland",
  "Krakow, Poland",
  "Lodz, Poland",
  "Lublin, Poland",
  "Katowice, Poland",
  "Wroklaw, Poland",
  "Poznan, Poland",
  "Szczecin, Poland",
  "Bialystok, Poland",
  "Belarus",
  "Minsk, Belarus",
  "Russia",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Kazan, Russia",
  "Novosibirsk, Russia",
  "Ekaterinburg, Russia",
  "Nizhny Novgorod, Russia",
  "Samara, Russia",
  "Rostov-on-Don, Russia",
  "Krasnoyarsk, Russia",
  "Perm, Russia",
  "Czechia",
  "Prague, Czechia",
  "Brno, Czechia",
  "Luxembourg",
  "Luxembourg, Luxembourg",
  "Netherlands",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Groningen, Netherlands",
  "Eindhoven, Netherlands",
  "Zwolle, Netherlands",
  "Belgium",
  "Brussels, Belgium",
  "Antwerp, Belgium",
  "Ghent, Belgium",
  "France",
  "Paris, France",
  "Lyon, France",
  "Toulouse, France",
  "Marseille, France",
  "Nantes, France",
  "Lille, France",
  "Bordeaux, France",
  "Grenoble, France",
  "Strasbourg, France",
  "Rennes, France",
  "Spain",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Malaga, Spain",
  "Bilbao, Spain",
  "Zaragoza, Spain",
  "Murcia, Spain",
  "Portugal",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Braga, Portugal",
  "Italy",
  "Milan, Italy",
  "Rome, Italy",
  "Turin, Italy",
  "Naples, Italy",
  "Bologna, Italy",
  "Florence, Italy",
  "Venice, Italy",
  "Genoa, Italy",
  "Pisa, Italy",
  "Trento, Italy",
  "Austria",
  "Vienna, Austria",
  "Graz, Austria",
  "Salzburg, Austria",
  "Linz, Austria",
  "Germany",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Stuttgart, Germany",
  "Dusseldorf, Germany",
  "Leipzig, Germany",
  "Dortmund, Germany",
  "Essen, Germany",
  "Hanover, Germany",
  "Nuremberg, Germany",
  "Dresden, Germany",
  "Bonn, Germany",
  "Karlsruhe, Germany",
  "Aachen, Germany",
  "Tubingen, Germany",
  "Switzerland",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Lausanne, Switzerland",
  "Bern, Switzerland",
  "Basel, Switzerland",
  "Bratislava",
  "Bratislava, Slovakia",
  "Slovenia",
  "Ljubljana, Slovenia",
  "Croatia",
  "Zagreb, Croatia",
  "Hungary",
  "Budapest, Hungary",
  "Debrecen, Hungary",
  "Szeged, Hungary",
  "Ukraine",
  "Kyiv, Ukraine",
  "Lviv, Ukraine",
  "Kharkiv, Ukraine",
  "Dnipro, Ukraine",
  "Odesa, Ukraine",
  "Romania",
  "Bucharest, Romania",
  "Cluj-Napoca, Romania",
  "Timisoara, Romania",
  "Iasi, Romania",
  "Brasov, Romania",
  "Craiova, Romania",
  "Republic of Moldova",
  "Chisinau, Republic of Moldova",
  "Serbia",
  "Belgrade, Serbia",
  "Novi Sad, Serbia",
  "Niš, Serbia",
  "Bosnia & Herzegovina",
  "Sarajevo, Bosnia & Herzegovina",
  "Bulgaria",
  "Sofia, Bulgaria",
  "Plovdiv, Bulgaria",
  "Varna, Bulgaria",
  "Kosovo",
  "Pristina, Kosovo",
  "North Macedonia",
  "Skopje, North Macedonia",
  "Albania",
  "Tirana, Albania",
  "Greece",
  "Athens, Greece",
  "Thessaloniki, Greece",
  "Patras, Greece"
]
