package com.example.be.entities.job;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@EqualsAndHashCode
@DynamoDBTable(tableName = "jobEntry")
public class BrowseJobEntry {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private @NonNull String ownerUsername;
    @DynamoDBAttribute
    private @NonNull String companyName;
    @DynamoDBAttribute
    private @NonNull String title;
    @DynamoDBAttribute
    private @NonNull String location;
    @DynamoDBAttribute
    private @NonNull String description;
    @DynamoDBAttribute
    private String salaryCurrency;
    @DynamoDBAttribute
    private List<Integer> salary;
    @DynamoDBAttribute
    private @NonNull List<String> tags;

    public static BrowseJobEntry of(JobEntry jobEntry) {
        return new BrowseJobEntry(
                jobEntry.getId(),
                jobEntry.getOwnerUsername(),
                jobEntry.getCompanyName(),
                jobEntry.getTitle(),
                jobEntry.getLocation(),
                jobEntry.getDescription(),
                jobEntry.getSalaryCurrency(),
                jobEntry.getSalary(),
                jobEntry.getTags()
        );
    }
}
