package com.example.be.entities.job;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.be.entities.base.IBaseEntity;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@DynamoDBTable(tableName = "jobReport")
public class JobReport implements IBaseEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String jobId;
    @DynamoDBAttribute
    private String posterUsername;
    @DynamoDBAttribute
    private String reason;
    @DynamoDBAttribute
    private String message;

    public JobReport(String jobId, String posterUsername, String reason, String message) {
        this.jobId = jobId;
        this.posterUsername = posterUsername;
        this.reason = reason;
        this.message = message;
    }
}
